#!/bin/bash
# 😉 Crédito: Felipe Facundes
#  Telegram: @FeFacundes
#  Telegram Group: t.me/winehq_linux

# user init scripts and settings
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_SESSION_TYPE=x11
xrdb $HOME/.Xresources
[ "$PATH" == *"$HOME/.local/bin"* ] || PATH="$HOME/.local/bin:$PATH"
vncserver &
freerdp-shadow-cli /sec:tls &
#-auth & # Esta opção inicia o freerdp sem autenticação e sem segurança.
#nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11 &
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &
#xset dpms 600 900 1200
#xset r rate 350 60

# launch the session
dbus-run-session openbox &
#anyremote -f /usr/share/anyremote/cfg-data/Server-mode/mouse.cfg -s socket:5197 &
#anyremote -f /usr/share/anyremote/cfg-data/Server-mode/smplayer.cfg -s socket:5197 &
tint2 &
pulseaudio -k &
pkill -9 pulseaudio &
#pulseaudio --disallow-exit --disable-shm &
pulseaudio --start &
start-pulseaudio-x11 &
# Checar se o volume está no mute e, restaurar o som a 100%
MUTE=$(LC_ALL=C pactl list sinks | grep -Ei yes | head -n 2 | cut -c 8-10)
if [ -e $MUTE ]; then
  pactl set-sink-volume 0 100%
else
  pactl set-sink-mute 0 toggle
fi
# Som de inicialização
export beep=~/.local/songs/midia-center-family-facundes.ogg
pactl upload-sample ~/.local/songs/midia-center-family-facundes.ogg
paplay "$beep" --volume=76767 && "$HOME"/.screenlayout/unica.sh &
#/usr/bin/crd --start &
#systemctl --user start chrome-remote-desktop &
volumeicon &
# Papel de Parede Aleatório
#while true; do nitrogen --set-zoom-fill "$(find $HOME/Imagens/Wallpapers/ -name '*[jJpP][nNpP][gG]' | shuf -n 1)"; sleep 10; done
while true; do nitrogen --set-zoom-fill "$(ls "$HOME"/Imagens/Wallpapers/*[jJpP][nNpP][gG] | shuf -n 1)"; sleep 10; done
#while true; do anyremote -f /usr/share/anyremote/cfg-data/Server-mode/all-in-one.cfg -s socket:5197 ; done
